#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# node scripts/bump-version.js $1

# exit 1 #abort commit

MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"
# Initialize constants here
export PATCH='(Fix: |Patch: )'
export MINOR='(Add: |Created: |New: |Feat: )'
export MAJOR='(Rework: |Release: )'
export OTHER='(Merge |Docs: |Style: |[skip CI])'

export ERROR_MSG="Commit message format must match regex \"${REGEX}\""

if [[ $FILE_CONTENT =~ $PATCH ]]; then
  npm version patch --no-git-tag-version
  printf "${GREEN}Bump patch!\n${BLACK}"
elif [[ $FILE_CONTENT =~ $MINOR ]]; then
  npm version minor --no-git-tag-version
  printf "${GREEN}Bump minor!\n${BLACK}"
elif [[ $FILE_CONTENT =~ $MAJOR ]]; then
  npm version major
  printf "${GREEN}Bump patch!\n${BLACK}"
elif [[ $FILE_CONTENT =~ $OTHER ]]; then
  printf "${GREEN}No bump needed!\n${BLACK}"
else
  printf "${RED}Bad commit ${BLUE}\"$FILE_CONTENT\"\n"
  printf "${YELLOW}$ERROR_MSG\n"
  printf "commit-msg hook failed (add --no-verify to bypass)\n"

  exit 1
fi

export CHANGED=$(git status -s package.json)
if [[ $CHANGED =~ "M package.json" ]]; then
  git add package.json package-lock.json
  git commit -m "[skip CI] Automated versioning bump"
fi
exit 0